title: Saroj Khadka
description: Security & DevOps Engineer from Nepal
url: "https://saroj345.github.io"
baseurl: ""
author: Saroj Khadka
email: hellosarojkhadka@gmail.com

permalink: /blog/:year/:month/:day/:title

# Exclude files from Jekyll processing
exclude:
  - README.md

# Markdown settings
markdown: kramdown
highlighter: rouge

kramdown:
  parse_block_html: true
  input: GFM

# Show posts with future dates
future: true
